### ISSUE TITLE
Error: unknown async library, or not in async context when using httpx

### ISSUE THREAD

**Issue by kulothunganug** [gottadiveintopython/asynckivy#104]
Hi, I am using `asynckivy` to use async/await instead of `threading`,
I want to use `httpx` library to request data from a API.

But it shows `Error: unknown async library, or not in async context`

Code:
```py
import asynckivy as ak
import httpx
from kivy.animation import Animation
from kivy.app import App
from kivy.lang import Builder

kv = """
BoxLayout:
    orientation: 'vertical'

    Label:
        id: anim_lbl
        text: "Animated label to check whether it is blocking the UI or not"
        font_size: 10
    
    Label:
        id: msg_lbl
        text: "Press below"
        size_hint: 1, 0.2
                    
    Button:
        text: "Load Data"
        size_hint: 1, 0.2
        on_press: app.fetch_data()
"""


class TestApp(App):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.data = []
        self.loading = False

    def build(self):
        return Builder.load_string(kv)

    def on_start(self):
        anim = Animation(font_size=10) + Animation(font_size=30)
        anim.repeat = True
        anim.start(self.root.ids.anim_lbl)

    def fetch_data(self):
        if not self.loading:
            self.loading = True
            self.root.ids.msg_lbl.text = "Loading Data..."
            ak.start(self.get_data_from_api())

    async def get_data_from_api(self):
        try:
            async with httpx.AsyncClient() as client:
                res = await client.get("https://jsonplaceholder.typicode.com/posts")
                self.data = res.json()

            await ak.sleep(2)

            self.loading = False
            self.root.ids.msg_lbl.text = "Data Loaded!"
        except Exception as e:
            self.loading = False
            self.root.ids.msg_lbl.text = f"Error: {str(e)}"
            print(f"Error: {str(e)}")


if __name__ == "__main__":
    TestApp().run()
```

If I rewrite the app with `asyncio`  instead of `asynckivy` it works well.
https://gist.github.com/kulothunganug/1c90a856f054e988b6ee3c91323e0f5e

I am new to this topic, if I did anything wrong the code, please correct me. Thanks

**Comment by kulothunganug** [comment]
I see, thanks for the information.

So I can't use httpx in a asynckivy app?
If yes, could you please write me a working example?

**Comment by gottadiveintopython** [comment]
> You cannot mix multiple async libraries in one function.

To be accurate, you cannot mix multiple async operations from different async libraries in one function. As long as all async operations in a function use the same async library, you can mix multiple async libraries.

```python
async def func():
    await asyncio.sleep(...)
    asynckivy.start(other_func())  # This is ok because this is not an async operation
    await asynckivy.sleep(...)  # This doesn't work because this is an async operation
```

**Comment by gottadiveintopython** [comment]
> So I can't use httpx in a asynckivy app?

You can. You need to run kivy in an async mode like you did in the example.
https://gist.github.com/kulothunganug/1c90a856f054e988b6ee3c91323e0f5e

**Comment by gottadiveintopython** [comment]
You can use `asyncio` and `asynckivy` at the same time. Just don't mix them in one function.

Also, take a look at this: https://github.com/gottadiveintopython/asynckivy#some-of-features-might-not-work-if-kivy-is-running-in-asynciotrio-mode

**Comment by kulothunganug** [comment]
Okay. Thanks for the knowledge and you time 😀
