### ISSUE TITLE
adding a picture asynchronously changes the photo to black

### ISSUE THREAD

**Issue by dEN5-tech** [gottadiveintopython/asynckivy#51]
![vue2U0BzWw](https://user-images.githubusercontent.com/54153548/136711303-f4fbea0b-feff-443e-b20d-4659e91bc687.gif)

**Comment by gottadiveintopython** [comment]
Well, it's hard to solve a problem without code. Post a minimal runnable code that re-produce the problem.

**Comment by dEN5-tech** [comment]
`def get_kivy_image_from_bytes(image_bytes, file_extension):
	# Return a Kivy image set from a bytes variable
	buf = io.BytesIO(image_bytes)
	cim = CoreImage(buf, ext=file_extension)
	return Image(texture=cim.texture).texture

def from_link_image_kivy(url):
	print(url)
	bimage = requests.get(url).content
	ext = "png"
	image = get_kivy_image_from_bytes(bimage, ext)
	return image

# 
kv = """
Image:
	
	 """

class TestApp(MDApp):
	def __init__(self, **kwargs):
		super().__init__(**kwargs)
		self.screen = Builder.load_string(kv)


	def create_rec(self):
		async def n():
			for i in [from_link_image_kivy("https://a108.agorov.org/uploads/posts/2021-10/1633190120_2-1.jpg")]:
				self.screen.texture = i
		ak.start(n())
	def build(self):
		return self.screen

	
	def on_start(self):
		async def n():
			 await ak.run_in_thread(lambda: self.create_rec())
		ak.start(n())

if __name__ == '__main__':
	TestApp().run()`

**Comment by gottadiveintopython** [comment]
I didn't test since you didn't provide runnable code, but the cause of the issue is you are touching Kivy from outside the main-thread. Don't do that.
